# Generated by Django 2.1.3 on 2018-12-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlehit',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
