# Generated by Django 2.1.3 on 2018-12-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0003_auto_20181213_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
