# Generated by Django 2.1.3 on 2018-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoring', '0004_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
